version: '3.8'

services:
  mockoon:
    platform: linux/arm64
    build:
      context: ./mockoon
      dockerfile: Dockerfile
    volumes:
      - ./mockoon/data:/usr/src/app/data
      - ./mockoon/swagger:/usr/src/app/swagger
    ports:
      - "3000:3000"
    restart: always

  nginx:
    platform: linux/arm64
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - mockoon
    restart: always

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /swagger/swagger.json
    volumes:
      - ./mockoon/swagger:/swagger
