version: '3.8'

services:
  mockoon:
    platform: linux/arm64
    build:
      context: ./mockoon
      dockerfile: Dockerfile
    volumes:
      - ./mockoon/data:/usr/src/app/data # 호스트의 ./mockoon/data 디렉토리를 컨테이너의 /usr/src/app/data에 마운트
    ports:
      - "3000:3000"
    restart: always

  nginx:
    platform: linux/arm64
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/html:/usr/share/nginx/html  # 호스트의 ./nginx/html 디렉토리를 컨테이너의 /usr/share/nginx/html에 마운트
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # NGINX 설정 파일을 덮어씀
    ports:
      - "80:80"
    depends_on:
      - mockoon
    restart: always
