# Use the official NGINX base image
FROM nginx:1.26.0

# Copy custom configuration file from the host to the container
COPY default.conf /etc/nginx/conf.d/default.conf

# Expose port 80 to the host
EXPOSE 80
